name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true cygnetops/react-test npm test
